fm_elfinder:
    instances:
        default:
            locale: fr # Langue
            editor: ckeditor # Editeur utilisé
            fullscreen: true # Taille d'affichage
            theme: smoothness # Thème à utiliser
            connector:
                roots:
                    uploads:
                        show_hidden: false # Masque les fichiers cachés
                        driver: LocalFileSystem # Pilote des fichiers
                        path: uploads # Chemin d'upload
                        upload_allow: ['image/png', 'image/webp', 'image/jpg', 'image/jpeg', 'image/gif', 'application/zip',
                                       'audio/mpeg', 'text/csv', 'video/mp4', 'video/webm',
                                       'application/pdf'] # Fichiers autorisés
                        upload_deny: ['all'] # Fichiers interdits
                        upload_max_size: 10M # Taille maximum
